//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutabkhana_DBLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_IssueBook
    {
        public int IssueBookID { get; set; }
        public int UserID { get; set; }
        [Required(ErrorMessage = "Please Select Book")]
        public int BookID { get; set; }
        [Required(ErrorMessage = "Please Select Employee")]
        public int EmployeeID { get; set; }
        [Required(ErrorMessage = "Please Enter No of Copies(Issue)!")]
        public int IssueCopies { get; set; }
        [Required(ErrorMessage = "Please Select Issue Date")]
        [DataType(DataType.Date)]
        public System.DateTime IssueDate { get; set; }
        [Required(ErrorMessage = "Please Select Return Date")]
        [DataType(DataType.Date)]
        public System.DateTime ReturnDate { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
        public bool ReserveNoOfCopies { get; set; }
    
        public virtual tbl_Book tbl_Book { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
    }
}
