//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutabkhana_DBLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Purchase()
        {
            this.tbl_PurchaseDetails = new HashSet<tbl_PurchaseDetails>();
        }
    
        public int PurchaseID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public int UserID { get; set; }
        public double PurchaseAmount { get; set; }
        public int SupplierID { get; set; }
    
        public virtual tbl_Supplier tbl_Supplier { get; set; }
        public virtual tbl_Users tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PurchaseDetails> tbl_PurchaseDetails { get; set; }
    }
}
